In [1]:
import numpy as np
my_arr = np.arange(1000000)
mylist = list(range(1000000))

In [19]:
%time for _ in range(10): my_arr = my_arr*2

CPU times: user 35.1 ms, sys: 3.64 ms, total: 38.7 ms
Wall time: 32.2 ms


In [5]:
%time for _ in range(10): mylist2 = [x*2 for x in mylist]

CPU times: user 589 ms, sys: 172 ms, total: 761 ms
Wall time: 760 ms


In [20]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)

In [21]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [22]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [23]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr2.ndim

2

In [25]:
arr2.shape

(2, 4)

In [26]:
arr2.dtype

dtype('int64')

In [27]:
print(np.zeros(10))
print(np.zeros((2,4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
np.empty((3,3,2))

array([[[ 4.66562981e-310,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [-5.60466303e+139,  6.93299937e-310]]])

In [34]:
np.arange??

In [36]:
np.arange(1,7,2,dtype = 'int')

array([1, 3, 5])

In [3]:
np.eye(4) # Gives an Identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
x = np.full((3,2),5) # Takes shape and fill value

In [17]:
np.full_like(x,1)

#Takes an array and fills with a - 
#value with same shape and same datatype

array([[1, 1],
       [1, 1],
       [1, 1]])

In [21]:
a = [[1,2,3],[4,5,6]]
np.empty_like(a) # Takes an Array and gives a Garbage filled 
# - array of same shape and Datatype

array([[94220398504220,              0,              0],
       [             0,              0,              0]])

In [27]:
arr1 = np.array([1,2,3], dtype = np.float64)
print(arr1)
arr2 = np.array([1.2,2.3,3.6], dtype = np.int64)
arr2

[1. 2. 3.]


array(['1.2', '2.3', '3.6'], dtype='<U3')

In [36]:
arr3 = arr1.astype(np.string_)
print(arr3)
# array2 = array1.astype(np.'required data_type')
arr3.dtype

[b'1.0' b'2.0' b'3.0']


dtype('S32')

In [37]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [43]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr*arr) # '*' is elementwise operator
print(arr+arr)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]


In [44]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [48]:
arr ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [49]:
arr4 = np.array([[1,3,1],[0,3,8]])
arr > arr4

array([[False, False,  True],
       [ True,  True, False]])

In [53]:
# Basic Indexing & Slicing
array1 = np.arange(10)
print(array1)
print(array1[5])
print(array1[5:8])
arr_slice = array1[2:7]
arr_slice

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]


array([2, 3, 4, 5, 6])

In [56]:
arr_slice[1] = 12345
print(array1)
# change made by assigning through index in
# - sliced array will result in base array
arr_slice1 = arr_slice[1:3]
print(arr_slice1)
arr_slice1 = arr_slice1*2
print(arr_slice)
print(array1)

[    0     1     2 12345     4     5     6     7     8     9]
[12345     4]
[    2 12345     4     5     6]
[    0     1     2 12345     4     5     6     7     8     9]


In [58]:
print(arr_slice1)

[24690     8]


In [60]:
arr_slice[:]= 64
print(arr_slice)
print(array1)

[64 64 64 64 64]
[ 0  1 64 64 64 64 64  7  8  9]


In [61]:
arr5 = array1[2:7].copy()
arr5
# arr5 is a copy. so any changes in arr5 will not 
# - result in original array

array([64, 64, 64, 64, 64])

In [63]:
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2d)
print(a2d[2])
print(a2d[0][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
3


In [3]:
a3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [70]:
print(a3d)
print(a3d[0])
print(a3d[1][0][1])
old_val = a3d[0].copy()

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
8


In [71]:
a3d[0]= 42
print(a3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [72]:
a3d[0]=old_val

In [5]:
print(a3d)
print(a3d[1,0])
print(a3d[1,0,0])
print(a3d[:1,1:])
a3d[:,:1]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[7 8 9]
7
[[[4 5 6]]]


array([[[1, 2, 3]],

       [[7, 8, 9]]])

In [8]:
names = np.array([["Abhi","Sai Anusha","Sailu"],["Abhi","Sanghamitra","Bindu"],["Abhi","Sri Devi","Nenu"]])
sel_list = [True,True,False]
names[:,sel_list] # Boolean Indexing

array([['Abhi', 'Sai Anusha'],
       ['Abhi', 'Sanghamitra'],
       ['Abhi', 'Sri Devi']], dtype='<U11')

In [32]:
# Additional array property
names = np.array(["ab","cd","ef","ab","ab","yz"])
cond = names == 'ab'
print(~cond)
names == 'ab'

[False  True  True False False  True]


array([ True, False, False,  True,  True, False])

In [33]:
mask = (names == 'ab') | (names == 'ef')
mask

array([ True, False,  True,  True,  True, False])

In [34]:
data = np.random.randn(7,4)

In [35]:
print(data)
data[data<0] = 0
print(data)

[[ 1.80428371 -0.20735052 -0.20938797 -0.97510219]
 [-1.05273538 -0.3022306  -0.11044757  1.14834718]
 [-0.9906554   0.51214832 -1.2988914  -1.178843  ]
 [-0.17664561 -2.24478657  1.57455577 -0.75947146]
 [-0.00924377 -0.35104828  1.63818163  1.32615972]
 [-0.96113127  0.78613734  1.67776772 -0.75721608]
 [ 0.01895278 -0.06876592  1.75647937 -0.22527938]]
[[1.80428371 0.         0.         0.        ]
 [0.         0.         0.         1.14834718]
 [0.         0.51214832 0.         0.        ]
 [0.         0.         1.57455577 0.        ]
 [0.         0.         1.63818163 1.32615972]
 [0.         0.78613734 1.67776772 0.        ]
 [0.01895278 0.         1.75647937 0.        ]]


In [36]:
arr = np.add_newdoc??

In [37]:
arr = np.empty((8,4))

In [38]:
for i in range(8):
    arr[i] = i

In [40]:
print(arr)
print(arr[[4,3,0,6]])
print(arr[[-3,-5,-7]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


In [41]:
arr = np.arange(32).reshape((8,4))

In [46]:
print(arr)
print(arr[[1,5,7,2],[0,3,1,2]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 23 29 10]


In [52]:
print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])
print(arr[[1, 5, 7, 2]][1:, [0, 3, 1, 2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
[[20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [64]:
arr = np.arange(16).reshape((4,4))
print(arr)
# Reshaping of an Array
# array2 = array1.reshape('new_shape')
arr1 = arr.reshape(16)
print(arr1)
arr1 = arr1.reshape((2,2,4))
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [67]:
# Transposing Linear and Quadratic Arrays
# array.T
print(arr.T)
# Matrix Product or Multiplication
# np.dot(array1,array2) or array1.dot(array2)
print(np.dot(arr,arr.T))
print(arr1)
# For Transposing Higher Dimensional Arrays
print(arr1.transpose((1,0,2)))

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[ 14  38  62  86]
 [ 38 126 214 302]
 [ 62 214 366 518]
 [ 86 302 518 734]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [8]:
import numpy as np
arr = np.arange(16).reshape((2, 2, 4))
print(arr.transpose((1, 0, 2)))
arr.swapaxes(1,2) # swapaxes similarly returns a view on the data without making a copy.

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [3]:
arr = np.matrix([[1,2,3],[4,5,6]])
print(arr)
print(arr+arr) # for np.matrices, * is used for matrix multiplication
print(arr*arr.T)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[14 32]
 [32 77]]
