In [1]:
import numpy as np

In [3]:
arr= np.arange(10)
arr1 = np.sqrt(arr)
arr2 = np.exp(arr)
print(arr1)
print(arr2)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [11]:
arr = np.random.randn(7)*5
arr1 = np.random.randn(7)*5

In [6]:
# np.modf(array_name) returns 2 arrays
# - with first one fractional part and the other integral part
frac_part,int_part=np.modf(arr)
# np.maximum(array1,array2) returns an array with maximum of
# each of the 2 corresponding places in the Arrays

In [9]:
print(arr)
print(frac_part)
print(int_part)

[ 1.90272841 -2.18078686 -1.01686188  5.17703501 -1.48466481  6.74683701
  3.63670571]
[ 0.90272841 -0.18078686 -0.01686188  0.17703501 -0.48466481  0.74683701
  0.63670571]
[ 1. -2. -1.  5. -1.  6.  3.]


In [12]:
# Binary Universal Functions
# array3 = np.add(array1,array2)
print(np.add(arr,arr1))
# array3 = np.subtract(array1,array2)
print(np.subtract(arr,arr1))
# array3 = np.multiply(array1,array2)
print(np.multiply(arr,arr1))
# array3 = np.divide(array1,array2)
# - or np.floor_divide(array1,array2).
# - It'll Truncate the Remainder
print(np.divide(arr,arr1))
# array3 =np.power(array1,array2). Raise array1 elements
# to the power of array2
print(np.power(arr,arr1))


[-5.25841273  8.25502062  8.73287279  3.18849587 16.43689999 -6.2363583
  6.52130245]
[  6.62421406   2.56519345  -5.17864694  -6.62128335 -11.82530456
   9.57020892   3.74204308]
[ -4.05732687  15.39128702  12.36117075  -8.41872181  32.58346333
 -13.17418345   7.13112483]
[-0.11494103  1.90167711  0.25548796 -0.34993524  0.16317182 -0.21091554
  3.69283472]
[9.64125992e+00 1.21872945e+02 5.45704770e+01            nan
 1.33987273e+05 1.76251901e-02 9.70503107e+00]


/tmp/ipykernel_4874/284245084.py:14: RuntimeWarning: invalid value encountered in power
  print(np.power(arr,arr1))


In [11]:
print(np.greater(arr2,arr1))
np.logical_or(arr1,arr2)

[ True  True  True  True  True  True  True  True  True  True]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [2]:
arr = np.random.randn(100)

In [3]:
(arr > 0).sum()

48

In [5]:
bools = np.array([True,False,True,False])
print(bools.all())
print(bools.any())

False
True


In [8]:
# Sorting
arr = np.random.randn(6)
arr1 = np.random.rand(5,3)

In [7]:
print(arr)
arr.sort()
print(arr)

[-0.1386652  -1.61224649 -1.45674391  0.24067747  0.01186217 -0.36436063]
[-1.61224649 -1.45674391 -0.36436063 -0.1386652   0.01186217  0.24067747]


In [9]:
arr2 = arr1
print(arr1)
arr1.sort(1)
print(arr1)

[[0.79569586 0.96425328 0.29610136]
 [0.16079988 0.07194902 0.22450317]
 [0.57580802 0.68451303 0.22015165]
 [0.57889212 0.05695583 0.29410313]
 [0.22450327 0.97102544 0.21931478]]
[[0.29610136 0.79569586 0.96425328]
 [0.07194902 0.16079988 0.22450317]
 [0.22015165 0.57580802 0.68451303]
 [0.05695583 0.29410313 0.57889212]
 [0.21931478 0.22450327 0.97102544]]


In [11]:
arr3 = arr2
arr2.sort(0)# If array2 = array1 then sorting array1 
print(arr3) # will also sort array2
print(arr2)

[[0.05695583 0.16079988 0.22450317]
 [0.07194902 0.22450327 0.57889212]
 [0.21931478 0.29410313 0.68451303]
 [0.22015165 0.57580802 0.96425328]
 [0.29610136 0.79569586 0.97102544]]
[[0.05695583 0.16079988 0.22450317]
 [0.07194902 0.22450327 0.57889212]
 [0.21931478 0.29410313 0.68451303]
 [0.22015165 0.57580802 0.96425328]
 [0.29610136 0.79569586 0.97102544]]


In [12]:
print(arr3)
arr3.sort()
print(arr3)

[[0.05695583 0.16079988 0.22450317]
 [0.07194902 0.22450327 0.57889212]
 [0.21931478 0.29410313 0.68451303]
 [0.22015165 0.57580802 0.96425328]
 [0.29610136 0.79569586 0.97102544]]
[[0.05695583 0.16079988 0.22450317]
 [0.07194902 0.22450327 0.57889212]
 [0.21931478 0.29410313 0.68451303]
 [0.22015165 0.57580802 0.96425328]
 [0.29610136 0.79569586 0.97102544]]


In [15]:
# np.sort(array) only returns a copy of array
# but never actually sorts the array
x1 = np.array([1,7,5,4,5])
print(np.sort(x1))
print(x1)

[1 4 5 5 7]
[1 7 5 4 5]


In [17]:
# Unique and Set Logic
names = np.array(['Abhi','Sri','Devi','Abhi','Devi','Devi','Raju'])
print(np.unique(names))
print(sorted(set(names)))

['Abhi' 'Devi' 'Raju' 'Sri']
['Abhi', 'Devi', 'Raju', 'Sri']


In [18]:
# np.in1d(array1,array2) returns a boolean array
# that tells that elements in array1 is present -
# in array2 or not
np.in1d(names,['Abhi','Devi','Raju'])
# Note : This is only for 1d arrays

array([ True, False,  True,  True,  True,  True,  True])